_wandb:
    value:
        cli_version: 0.23.0
        code_path: code/src/train_RL_with_BC_max_wandb.py
        e:
            2vjm2dul2gl9yjnhh8k62yrgyu8lukhl:
                codePath: src/train_RL_with_BC_max_wandb.py
                codePathLocal: train_RL_with_BC_max_wandb.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.0"
                disk:
                    /:
                        total: "934505979904"
                        used: "28839776256"
                email: gawtamcr3@gmail.com
                executable: /Midgard/home/gawtam/miniforge3/envs/stl/bin/python
                git:
                    commit: 3aadc9e7b45783912450a7fe8c6c266dc5b088fb
                    remote: https://github.com/gawtamcr/crgstl.git
                gpu: NVIDIA GeForce RTX 3080
                gpu_count: 6
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-b6719ce7-96ea-d0a3-8d76-1625133fc2f0
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-fdd55492-3a91-6a7a-610d-a07d0a69755c
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-cfa7601a-67c7-83aa-be3b-22ad418732f5
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-f42406f6-cdf8-0b06-3a53-e8d1b605de5f
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-40a65a05-5ad4-b77d-fc87-1ae682bbc85f
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-7a904906-cca0-e594-e382-c5e259b182a3
                host: arwen
                memory:
                    total: "540912373760"
                os: Linux-5.10.0-21-amd64-x86_64-with-glibc2.31
                program: /Midgard/home/gawtam/crgstl/src/train_RL_with_BC_max_wandb.py
                python: CPython 3.10.19
                root: ./../models/training/
                slurm:
                    checkpoint_image_dir: /var/slurm/checkpoint
                    cluster_name: rpl_cluster
                    cpus_on_node: "12"
                    cpus_per_task: "12"
                    gtids: "0"
                    job_account: defaultusr
                    job_cpus_per_node: "12"
                    job_gid: "1295200087"
                    job_gpus: 3,4,5,6
                    job_id: "874571"
                    job_name: run.sbatch
                    job_nodelist: arwen
                    job_num_nodes: "1"
                    job_partition: pdebug
                    job_qos: normal
                    job_uid: "1295200087"
                    job_user: gawtam
                    jobid: "874571"
                    localid: "0"
                    mem_per_node: "131072"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: arwen
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /Midgard/home/gawtam/crgstl/src
                    submit_host: moria
                    task_pid: "2376592"
                    tasks_per_node: "1"
                    topology_addr: arwen
                    topology_addr_pattern: node
                    working_cluster: rpl_cluster:slurmctl1.rpl:6817:8192
                startedAt: "2026-02-17T11:45:19.549953Z"
                writerId: 2vjm2dul2gl9yjnhh8k62yrgyu8lukhl
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.10.19
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
algo:
    value: SAC
batch_size:
    value: 2048
buffer_size:
    value: 100000
learning_rate:
    value: 0.0003
timesteps:
    value: 200000
